{
 "title": "Pedidos Veloz - visão operacional",
 "tags": [
  "loja-veloz",
  "microservicos"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (servico) (rate(http_requisicoes_total[5m]))",
     "legendFormat": "{{servico}}"
    }
   ]
  },
  {
   "title": "Latência p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, servico) (rate(http_duracao_segundos_bucket[5m])))",
     "legendFormat": "p95 {{servico}}"
    }
   ]
  },
  {
   "title": "Respostas HTTP nos últimos 15 minutos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_requisicoes_total[15m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Logs dos serviços",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{projeto=\"pedidos-veloz\"}"
    }
   ]
  }
 ]
}