apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - {name: gateway, count: 2}
  - {name: pedidos, count: 2}
  - {name: estoque, count: 2}
  - {name: pagamentos, count: 2}
